- name: Load Maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load SQL File
  ansible.builtin.shell: mysql -h mysql-{{ env }}.tejadevopsb81.icu -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data

- name: Restart Shipping Service
  ansible.builtin.systemd_service:
    name: shipping
    state: restarted
    enabled: true