- name: Copy RabbitMQ Repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install RabbitMQ Server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: Add Application User
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/rabbitmq:user token={{ vault_token }} url=http://vault-internal.tejadevopsb81.icu:8200')}}"
    password: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/rabbitmq:password token={{ vault_token }} url=http://vault-internal.tejadevopsb81.icu:8200')}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present