- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Setup MySQL Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('hashi_vault', 'roboshop-{{env}}/data/mysql:mysql_root_password token={{ vault_token }} url=http://vault-internal.tejadevopsb81.icu:8200')}}