- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Setup MySQL Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1