- name: Load NodeJS
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: Load Master Data
  ansible.builtin.shell: mongosh --host mongodb-{{env}}.tejadevopsb81.icu </app/db/master-data.js

- name: Restart Catalogue Service
  ansible.builtin.systemd_service:
    name: catalogue
    state: restarted