- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Load App Prerequisites
  ansible.builtin.include_tasks:
    file: app_prerequisites.yml

- name: Install Maven dependencies
  ansible.builtin.shell: mvn clean package; mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app

- name: SystemD setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml