- name: Copy the Service File
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Start Application Service File
  ansible.builtin.systemd_service:
    name: "{{component}}"
    state: restarted
    enabled: true
    daemon_reload: true